FROM node: 18-alpine as builder
WORKDIR /app/react_fast

COPY ./react/package.json ./
RUN npm i

COPY ./react .
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/react/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
